export const chooseArtistData = [
    {
        title:'Artist/Creator',
        path:'/ChooseArtist/choose1.png'
    },
    {
        title:'Artist/Creator',
        path:'/ChooseArtist/choose2.png'
    },
    {
        title:'Artist/Creator',
        path:'/ChooseArtist/choose3.png'
    },
    {
        title:'Artist/Creator',
        path:'/ChooseArtist/choose4.png'
    },
    {
        title:'Artist/Creator',
        path:'/ChooseArtist/choose5.png'
    },
    {
        title:'Artist/Creator',
        path:'/ChooseArtist/choose6.png'
    },
    {
        title:'Artist/Creator',
        path:'/ChooseArtist/choose7.png'
    },
    {
        title:'Artist/Creator',
        path:'/ChooseArtist/choose8.png'
    },
    {
        title:'Artist/Creator',
        path:'/ChooseArtist/choose9.png'
    },
]